#!C:\Users\rabiy\Downloads\Selenium Automation with Google_Recaptcha_v2\SeleniumAutomation\env\Scripts\python.exe
# Copyright 2014-2017, Damian Johnson and The Tor Project
# See LICENSE for licensing information

import stem.interpreter

if __name__ == '__main__':
  stem.interpreter.main()
